In [1]:
import os
os.getcwd()

'C:\\Users\\prath'

In [7]:
#THE LIBRARIES TO BE ADDED
import os
import cv2
import numpy as np
from PIL import Image, ImageOps
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential,load_model
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10

(a,b),(c,d)=cifar10.load_data()


#Dir_rice="D:\Hackathon\diseases_dataset\image data\test\Rice"
#Dir_tomato="D:\Hackathon\diseases_dataset\image data\test\tomato"
#Categ_corn=["cercospora leaf spot gray leaf spot","common rust","healthy","northern leaf blight"]
#Categ_rice=["BrownSpot","Healthy","Hispa","LeafBlast"]
#Categ_tomato=["bacterial spot","early blight","healthy","late blight","leaf mold","septoria leaf spot"]# HAVE TO ADD MORE AFTER TESTING

D:\Hackathon\diseases_dataset\image_data\test


In [20]:
#_corn=["cercospora leaf spot gray leaf spot","common rust","healthy","northern leaf blight"]
#Categ_rice=["BrownSpot","Healthy","Hispa","LeafBlast"]
#Categ_tomato=["bacterial spot","early blight","healthy","late blight","leaf mold","septoria leaf spot"]# HAVE TO ADD MORE AFTER TESTING
#for ca_rice in Categ_rice:
#    path_rice=os.path.join(Dir_corn,ca_rice)
#    print(path_rice)

Dir = "D:\Hackathon\diseases_dataset\image_data\\test"
print(Dir)
    
crops=['rice','corn','tomato']   

for crop in crops:
    
    data_path=os.path.join(Dir,crop)
    
    model = load_model(os.path.join(Dir,'keras_model.h5'),compile=False)

    # Create the array of the right shape to feed into the keras model
    # The 'length' or number of images you can put into the array is
    # determined by the first position in the shape tuple, in this case 1.
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    # Replace this with the path to your image
    image = Image.open("D:\RiceBlast1.jpg")
    #resize the image to a 224x224 with the same strategy as in TM2:
    #resizing the image to be at least 224x224 and then cropping from the center
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.ANTIALIAS)

    #turn the image into a numpy array
    image_array = np.asarray(image)
    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    # Load the image into the array
    data[0] = normalized_image_array

    # run the inference
    prediction = model.predict(data)
    print(prediction)

D:\Hackathon\diseases_dataset\image_data\test
[[0.9988708  0.00112918]]
[[0.9988708  0.00112918]]
[[0.9988708  0.00112918]]


In [19]:
data


array([[[[-7.40196251e-37,  5.98354444e-43, -1.20182910e-34],
         [ 5.98354444e-43,  9.44881916e-01,  9.84251976e-01],
         [ 9.52755928e-01,  9.60629940e-01,  1.00787401e+00],
         ...,
         [ 3.18326354e-02, -4.59266827e-03, -3.60722803e-02],
         [-3.82615179e-02, -8.11195374e-03,  5.51971942e-02],
         [-4.74118516e-02,  2.12092400e-02,  3.84388342e-02]],

        [[-2.62649581e-02,  1.77000090e-02,  5.03588021e-02],
         [-4.44686152e-02,  2.13090330e-02,  1.99779347e-02],
         [ 3.06644514e-02, -4.27210405e-02,  4.79242653e-02],
         ...,
         [ 4.20905277e-02,  4.60239053e-02,  3.58579606e-02],
         [-4.27402332e-02,  5.14872372e-03,  1.55236199e-02],
         [ 2.35877112e-02, -4.98312339e-02,  8.77879560e-03]],

        [[ 5.99441975e-02, -6.06444031e-02,  3.28924507e-03],
         [ 3.57077569e-02,  8.14609230e-03,  2.48131901e-02],
         [-6.13881834e-02, -2.91555561e-02, -2.08866671e-02],
         ...,
         [ 3.83451208e-0